# Coursework 2
(core codebase to be imported as modules)

In [1]:
import numpy as np

from kernels import polynomial_kernel
from perceptron import Perceptron, KernelPerceptron

In [2]:
# Loading Data
data = np.loadtxt("dtrain123.dat")
y = data[:, 0]
X = data[:, 1:]

In [3]:
# Build test XOR dataset
a = np.array([[1,1], [-1,-1], [-1,1], [1,-1]])
b = np.array([1,1,-1,-1])

In [4]:
# Run for regular unkernalised perceptron
p = Perceptron()
p.train(a, b)
p.predict(a)

array([ 0.,  0.,  0.,  0.])

In [5]:
# Run for 2-order polynomial kernel
p_2 = KernelPerceptron(polynomial_kernel, 2)
p_2.train(a,b)
p_2.predict_proba(a)

array([ 4.,  4., -8., -8.])

In [6]:
p_2.gram

array([[4, 4, 0, 0],
       [4, 4, 0, 0],
       [0, 0, 4, 4],
       [0, 0, 4, 4]])

## Test for differentiating between 1s and 3s

In [7]:
idx = y!=2
X_z = X[idx,:]
y_z = y[idx]
n_1 = sum(y==1)
n_3 = sum(y==3)
print(n_1, n_3)

120 70


### Regular perceptron

In [8]:
p = Perceptron()
p.train(X_z, y_z)
p.predict_proba(X_z)

array([ 606.139521,  432.104409,  285.106062,  297.065196,  280.815102,
        289.482297,  274.082505,  422.953713,  276.683301,  499.11159 ,
        279.929796,  400.439325,  277.890516,  444.535866,  489.853938,
        275.019225,  469.146744,  453.711327,  273.672306,  281.760915,
        408.164151,  298.688094,  288.772134,  265.534653,  277.679397,
        268.36293 ,  288.929082,  336.760827,  338.973021,  290.760453,
        430.915659,  366.433137,  260.957778,  276.964329,  279.903555,
        288.826521,  403.524498,  436.493814,  281.314353,  277.492206,
        272.581605,  275.642601,  282.015756,  288.184458,  269.271132,
        321.696468,  249.548715,  287.874354,  276.19812 ,  435.758532,
        288.416805,  285.88734 ,  280.336749,  456.162555,  276.069846,
        286.78917 ,  281.739432,  277.520337,  279.989538,  275.122434,
        282.207699,  295.468731,  377.506497,  267.878319,  335.091168,
        270.44613 ,  324.05244 ,  278.820402,  289.447668,  348.

In [9]:
X_z.shape

(190, 256)

In [10]:
### Polynomial Kernel
d = 4
p_4 = KernelPerceptron(kernel=polynomial_kernel, k_params=d)
p_4.train(X_z, y_z)

In [13]:
p_4.predict(X_z)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1